export const SELECT_NODE = "SELECT_NODE";
export const SELECT_LINE = "SELECT_LINE";
export const SELECT_CONNECTION_TYPE = "SELECT_CONNECTION_TYPE"
export const SELECT_METER_TYPE = "SELECT_METER_TYPE"
export const POWER_TOGGLE = "POWER_TOGGLE"
export const SELECT_EXERCISE = "SELECT_EXERCISE"
export const JUMPER_TOGGLE = "JUMPER_TOGGLE"
export const DOWNLOAD_GRAPH = "DOWNLOAD_GRAPH"
